name: uhg
channels:
  - pytorch
  - pyg
  - apple
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - pip
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pyg::pytorch-geometric
  - numpy>=1.19.0
  - scipy>=1.5.0
  - networkx>=2.5
  - tqdm>=4.50.0
  - matplotlib>=3.3.0
  - scikit-learn>=0.24.0
  # Mac Silicon specific
  - tensorflow-deps
  - pip:
    - tensorflow-macos
    - tensorflow-metal
    - -e . 