name: uhg
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - pip
  - pytorch>=1.7.0
  - pytorch-geometric>=2.0.0
  - numpy>=1.19.0
  - scipy>=1.5.0
  - networkx>=2.5
  - tqdm>=4.50.0
  - matplotlib>=3.3.0
  - scikit-learn>=0.24.0
  - pip:
    - -e . 