[tox]
envlist = py310, py311, py312, lint, type
isolated_build = True

[testenv]
usedevelop = true
extras = dev
commands =
    pytest tests --cov=uhg --cov-report=term-missing --cov-fail-under=25 {posargs}

[testenv:lint]
usedevelop = true
extras = dev
commands =
    black --check uhg tests

[testenv:type]
usedevelop = true
extras = dev
commands =
    mypy uhg

[flake8]
max-line-length = 88
extend-ignore = E203
exclude =
    .tox,
    .git,
    __pycache__,
    build,
    dist,
    *.pyc,
    *.egg-info,
    .eggs
